// Generated by CoffeeScript 1.4.0
(function() {
  var httpUtil;

  httpUtil = require('../lib/http');

  httpUtil.post({
    host: 'https://login.taobao.com',
    path: '/member/login.jhtml',
    data: {
      TPL_username: 'username',
      TPL_password: 'password'
    },
    log: true,
    decode: true
  }, function(err, data, res) {
    if (err) {
      return console.error(err);
    } else {
      console.log(res.statusCode);
      return console.log(res.headers);
    }
  });

}).call(this);
